--- 
Title: service
Type: test
Protocol: http
Version: "0.1"
Domain: duckbunny
APIDefinition:
    Type: swagger
    LocationType: vcs
    VCS:
        Type: git
        Location: https://github.com/duckbunny/service.git
        File: definition.json
Configs: 
  - 
    Key: testconfig1
    Description: "My first test config"
    Required: false
  - 
    Key: testconfig2
    Description: "My second test config"
    Required: true
Private: false
Requires: 
  - 
    Domain: duckbunny
    Title: service2
    Version: "0.1"
  - 
    Domain: duckbunny
    Title: service3
    Version: "0.1"
Flags: 
  - 
    Key: "test"
    Env: "TESTVAR"
    Description: "This is a test flag."
    Required: true
